// <auto-generated />
using System;
using AuroraHRMPWA.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuroraHRMPWA.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220402201938_EmploymentDetails")]
    partial class EmploymentDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AuroraHRMPWA.Shared.EmploymentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfHiring")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoticePeriod")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmploymentDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalary = 6500m,
                            DateOfHiring = new DateTime(2022, 4, 3, 4, 19, 38, 482, DateTimeKind.Local).AddTicks(4029),
                            Department = "Engineering",
                            NoticePeriod = 6,
                            Position = "Engineering lead",
                            UserId = 29
                        },
                        new
                        {
                            Id = 2,
                            BaseSalary = 3500m,
                            DateOfHiring = new DateTime(2022, 4, 3, 4, 19, 38, 482, DateTimeKind.Local).AddTicks(4043),
                            Department = "Engineering",
                            NoticePeriod = 6,
                            Position = "Software Engineer",
                            UserId = 31
                        },
                        new
                        {
                            Id = 3,
                            BaseSalary = 3100m,
                            DateOfHiring = new DateTime(2022, 4, 3, 4, 19, 38, 482, DateTimeKind.Local).AddTicks(4044),
                            Department = "Human Resource",
                            NoticePeriod = 6,
                            Position = "HR Executive",
                            UserId = 37
                        },
                        new
                        {
                            Id = 4,
                            BaseSalary = 5100m,
                            DateOfHiring = new DateTime(2022, 4, 3, 4, 19, 38, 482, DateTimeKind.Local).AddTicks(4046),
                            Department = "Human Resource",
                            NoticePeriod = 6,
                            Position = "HR Manager",
                            UserId = 43
                        });
                });

            modelBuilder.Entity("AuroraHRMPWA.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AuroraHRMPWA.Shared.EmploymentDetail", b =>
                {
                    b.HasOne("AuroraHRMPWA.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
